services:
  workshop:
    container_name: workshop
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
      secrets:
        - known_hosts
    secrets:
      - source: ssh_key
        target: /root/.ssh/id_ed25519
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # - ../website:/app/website:rw

secrets:
  known_hosts:
    file: ~/.ssh/known_hosts
  ssh_key:
    file: ~/.ssh/id_ed25519
